apiVersion: v1
kind: Service
metadata:
  labels:
    app: korifi-api
  name: svc
  annotations:
    projectcontour.io/upstream-protocol.tls: "443"
spec:
  type: ClusterIP
  ports:
  - port: 443
    protocol: TCP
    targetPort: web
    name: web
  selector:
    app: korifi-api
