# The CF Organization Manager Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: organization-manager
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cforgs
  verbs:
  - get
  - list
  - watch
