# The CF Root Namespace User
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: root-namespace-user
  annotations:
    hncv1alpha2.AnnotationNoneSelector: "true"
rules:
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfdomains
  verbs:
  - get
  - list

- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cforgs
  verbs:
  - get
  - list
  - watch
